version: '3.2'

services:
  web:
    container_name: stock2shop_web
    build: ./docker/nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80
    links:
      - php
    networks:
      - stock-2-shop-network

  mysql:
    container_name: stock2shop_mysql
    build: ./docker/mysql
    restart: always
    ports:
      - 3302:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stock2shop123
      MYSQL_DATABASE: stock_2_shop
    networks:
      - stock-2-shop-network

  php:
    container_name: stock2shop_php
    build: ./docker/php
    links:
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - 9013:9000
    networks:
      - stock-2-shop-network

networks:
  stock-2-shop-network:
    driver: bridge

volumes:
  data:
    driver: local